spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true

flyway.locations: classpath:db/migration

quartz.enabled: true

samplejob.frequency: 2000